INSERT INTO permissions (id, module, action, description) VALUES
    ('subscriptions:view', 'subscriptions', 'view', 'View SACCO subscription packages, invoices, and billing status.'),
    ('subscriptions:manage', 'subscriptions', 'manage', 'Record subscription payments and manage billing access.'),
    ('dashboard:view', 'dashboard', 'view', 'View role-scoped dashboard metrics.');

INSERT INTO roles (id, tenant_id, name, protected_role, created_by_user_id) VALUES
    ('role_platform_super_admin', 'tenant_platform', 'Platform Super Admin', TRUE, 'user_platform_admin'),
    ('role_platform_operations_officer', 'tenant_platform', 'Platform Operations Officer', TRUE, 'user_platform_admin'),
    ('role_platform_billing_officer', 'tenant_platform', 'Platform Billing Officer', TRUE, 'user_platform_admin'),
    ('role_platform_compliance_officer', 'tenant_platform', 'Platform Compliance Officer', TRUE, 'user_platform_admin'),
    ('role_platform_support_officer', 'tenant_platform', 'Platform Support Officer', TRUE, 'user_platform_admin'),
    ('role_green_accountant', 'tenant_green', 'Accountant', TRUE, 'user_green_admin'),
    ('role_green_teller', 'tenant_green', 'Teller / Cashier', TRUE, 'user_green_admin'),
    ('role_green_auditor', 'tenant_green', 'Auditor', TRUE, 'user_green_admin');

INSERT INTO role_permissions (role_id, permission_id)
SELECT role_id, permission_id
FROM (
    VALUES
        ('role_platform_admin', 'dashboard:view'),
        ('role_platform_admin', 'subscriptions:view'),
        ('role_platform_admin', 'subscriptions:manage'),
        ('role_platform_super_admin', 'dashboard:view'),
        ('role_platform_super_admin', 'tenants:view'),
        ('role_platform_super_admin', 'tenants:manage'),
        ('role_platform_super_admin', 'subscriptions:view'),
        ('role_platform_super_admin', 'subscriptions:manage'),
        ('role_platform_super_admin', 'users:view'),
        ('role_platform_super_admin', 'users:create'),
        ('role_platform_super_admin', 'roles:view'),
        ('role_platform_super_admin', 'roles:create'),
        ('role_platform_super_admin', 'members:view'),
        ('role_platform_super_admin', 'transactions:view'),
        ('role_platform_super_admin', 'transactions:create'),
        ('role_platform_super_admin', 'transactions:approve'),
        ('role_platform_super_admin', 'loans:view'),
        ('role_platform_super_admin', 'loans:create'),
        ('role_platform_super_admin', 'loans:approve'),
        ('role_platform_super_admin', 'accounting:view'),
        ('role_platform_super_admin', 'accounting:post'),
        ('role_platform_super_admin', 'reports:view'),
        ('role_platform_super_admin', 'approvals:view'),
        ('role_platform_super_admin', 'approvals:decide'),
        ('role_platform_super_admin', 'operations:view'),
        ('role_platform_super_admin', 'notifications:view'),
        ('role_platform_super_admin', 'notifications:manage'),
        ('role_platform_super_admin', 'governance:view'),
        ('role_platform_super_admin', 'governance:manage'),
        ('role_platform_super_admin', 'complaints:view'),
        ('role_platform_super_admin', 'complaints:manage'),
        ('role_platform_operations_officer', 'dashboard:view'),
        ('role_platform_operations_officer', 'tenants:view'),
        ('role_platform_operations_officer', 'members:view'),
        ('role_platform_operations_officer', 'transactions:view'),
        ('role_platform_operations_officer', 'loans:view'),
        ('role_platform_operations_officer', 'approvals:view'),
        ('role_platform_operations_officer', 'reports:view'),
        ('role_platform_operations_officer', 'operations:view'),
        ('role_platform_operations_officer', 'notifications:view'),
        ('role_platform_operations_officer', 'complaints:view'),
        ('role_platform_billing_officer', 'dashboard:view'),
        ('role_platform_billing_officer', 'tenants:view'),
        ('role_platform_billing_officer', 'subscriptions:view'),
        ('role_platform_billing_officer', 'subscriptions:manage'),
        ('role_platform_billing_officer', 'reports:view'),
        ('role_platform_billing_officer', 'operations:view'),
        ('role_platform_compliance_officer', 'dashboard:view'),
        ('role_platform_compliance_officer', 'tenants:view'),
        ('role_platform_compliance_officer', 'transactions:view'),
        ('role_platform_compliance_officer', 'loans:view'),
        ('role_platform_compliance_officer', 'accounting:view'),
        ('role_platform_compliance_officer', 'reports:view'),
        ('role_platform_compliance_officer', 'operations:view'),
        ('role_platform_compliance_officer', 'approvals:view'),
        ('role_platform_support_officer', 'dashboard:view'),
        ('role_platform_support_officer', 'tenants:view'),
        ('role_platform_support_officer', 'members:view'),
        ('role_platform_support_officer', 'reports:view'),
        ('role_platform_support_officer', 'operations:view'),
        ('role_platform_support_officer', 'complaints:view'),
        ('role_platform_support_officer', 'notifications:view'),
        ('role_green_admin', 'dashboard:view'),
        ('role_green_admin', 'subscriptions:view'),
        ('role_green_treasurer', 'dashboard:view'),
        ('role_green_secretary', 'dashboard:view'),
        ('role_green_chairperson', 'dashboard:view'),
        ('role_green_accountant', 'dashboard:view'),
        ('role_green_accountant', 'transactions:view'),
        ('role_green_accountant', 'transactions:create'),
        ('role_green_accountant', 'accounting:view'),
        ('role_green_accountant', 'accounting:post'),
        ('role_green_accountant', 'reports:view'),
        ('role_green_accountant', 'operations:view'),
        ('role_green_teller', 'dashboard:view'),
        ('role_green_teller', 'members:view'),
        ('role_green_teller', 'transactions:view'),
        ('role_green_teller', 'transactions:create'),
        ('role_green_auditor', 'dashboard:view'),
        ('role_green_auditor', 'members:view'),
        ('role_green_auditor', 'transactions:view'),
        ('role_green_auditor', 'loans:view'),
        ('role_green_auditor', 'accounting:view'),
        ('role_green_auditor', 'reports:view'),
        ('role_green_auditor', 'operations:view'),
        ('role_green_auditor', 'approvals:view')
) AS grants(role_id, permission_id);

INSERT INTO user_roles (user_id, role_id, tenant_id) VALUES
    ('user_platform_admin', 'role_platform_super_admin', 'tenant_platform');
