CREATE TABLE loans (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL REFERENCES tenants(id),
    member_id VARCHAR(64) NOT NULL REFERENCES members(id),
    product VARCHAR(80) NOT NULL,
    amount DECIMAL(18, 2) NOT NULL,
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(80) NOT NULL,
    guarantors INTEGER NOT NULL DEFAULT 0,
    dsr INTEGER NOT NULL DEFAULT 0,
    repayment_months INTEGER NOT NULL,
    purpose VARCHAR(240),
    channel VARCHAR(32) NOT NULL,
    submitted_by_member_id VARCHAR(64),
    approved_by_user_id VARCHAR(64),
    approved_at TIMESTAMP WITH TIME ZONE,
    disbursed_by_user_id VARCHAR(64),
    disbursed_at TIMESTAMP WITH TIME ZONE,
    rejection_reason VARCHAR(240),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_loans_tenant_status ON loans (tenant_id, status);
CREATE INDEX idx_loans_member_created ON loans (member_id, created_at DESC);

INSERT INTO loans (
    id,
    tenant_id,
    member_id,
    product,
    amount,
    balance,
    status,
    stage,
    guarantors,
    dsr,
    repayment_months,
    purpose,
    channel,
    disbursed_by_user_id,
    disbursed_at
) VALUES
    (
        'loan_green_0001',
        'tenant_green',
        'member_green_amina',
        'Development Loan',
        3000000,
        2150000,
        'active',
        'Disbursed',
        2,
        31,
        12,
        'Business expansion',
        'staff',
        'user_green_admin',
        TIMESTAMP WITH TIME ZONE '2026-07-10 10:00:00+00'
    ),
    (
        'loan_green_0002',
        'tenant_green',
        'member_green_daniel',
        'Emergency Loan',
        800000,
        800000,
        'under_review',
        'Credit Appraisal',
        1,
        44,
        6,
        'Medical emergency',
        'staff',
        NULL,
        NULL
    ),
    (
        'loan_lake_0001',
        'tenant_lake',
        'member_lake_peter',
        'Agriculture Loan',
        1500000,
        0,
        'submitted',
        'Guarantor Review',
        0,
        27,
        10,
        'Farm inputs',
        'staff',
        NULL,
        NULL
    );
